language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t tzduid/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tzduid/docker-react npm run test
  - 